-- confirmation of database being loaded from jupyter.
Select
*
From
customer
Limit 10

-- Q1. What is the total revenue generated by male vs female customers?
Select
gender,
SUM(purchase_amount) as revenue
From
customer
Group by
gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

Select
customer_id,
purchase_amount
From
customer
Where
discount_applied = 'Yes' AND purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?

Select
item_purchased,
round(Avg(review_rating::numeric),3) as "average"
From
customer
group by
item_purchased
order by
avg(review_rating) DESC
limit 5

--Q4. Compare the average purchase amount between standard and express shipping.

select
shipping_type,
Round(avg(purchase_amount),3) as "average"
from
customer
where
shipping_type IN ('Standard', 'Express')
group by
shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select
subscription_status,
count(customer_id),
round(sum(purchase_amount),3) as "total revenue",
round(avg(purchase_amount),3) as "average spend"
from 
customer
group by
subscription_status
order by
"total revenue", "average spend" DESC

--Q6. Which 5 products have the highest percentage of purchases with discount applied?

select
item_purchased,
round(100.00 * sum(Case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from
customer
group by
item_purchased
order by
discount_rate DESC
Limit 5

--Q7. Segment customers into New, Returning, and Loyal 
-- based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select
customer_id,
previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)

select
customer_segment,
count(*) as "total number"
from
customer_type
group by
customer_segment
order by
"total number" DESC

--Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select
category,
item_purchased,
Count(customer_id) as total_orders,
Row_number() over (partition by category order by count(customer_id)DESC) as item_rank

-- we can use dense_rank() instead of row_number(), 
-- there can be two or more categories which tied the same rank within top 3,
-- and if we want those categories to show up, we used dense_rank() or rank(),
-- query: Dense_rank() over (partition by category order by count(customer_id)DESC) as item_rank

from customer
group by category, item_purchased
)

select
item_rank,
category,
item_purchased,
total_orders
from
item_counts
where
item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select
subscription_status,
count(customer_id) as repeat_buyers
from
customer
where
previous_purchases > 5
group by
subscription_status

--Q10. What is the revenue contribution of each age group?

select
"age group",
SUM(purchase_amount) as "revenue contribution"
from customer
group by
"age group"
order by
"revenue contribution" DESC

-- Verification queries: used to confirm/correct dashboard and report insights
-- A. Gender revenue split (total and % of overall revenue)

SELECT gender,
       ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue,
       ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS pct_of_total
FROM customer
GROUP BY gender;

-- B. Gender: customer count and average spend per customer
-- (checks whether the revenue gap above is driven by customer volume or by individual spending behavior)


SELECT gender, COUNT(*) AS customer_count, ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase
FROM customer
GROUP BY gender;

-- C. Shipping type: average purchase amount, standard vs express

SELECT shipping_type,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- D. Subscription status: average spend and customer count

SELECT subscription_status,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase,
       COUNT(*) AS customer_count
FROM customer
GROUP BY subscription_status;

-- E. Subscription status: average previous purchases (repeat-purchase / loyalty proxy)

SELECT subscription_status, ROUND(AVG(previous_purchases)::numeric, 2) AS avg_previous_purchases
FROM customer
GROUP BY subscription_status;

